version: "3.9"
services:
  frontend:
    image: gcr.io/google-samples/microservices-demo/frontend:v0.10.0
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      # Esta variable es OBLIGATORIA para que el frontend no se apague
      - SHOPPING_ASSISTANT_SERVICE_ADDR=localhost:8080
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
    depends_on:
      - productcatalogservice
      - currencyservice
      - cartservice
      - recommendationservice
      - shippingservice
      - checkoutservice
      - adservice

#   shoppingassistantservice:
#     image: gcr.io/google-samples/microservices-demo/shoppingassistantservice:v0.10.0
#     ports:
#       - "8081:8080"
#     environment:
#       - PORT=8080
#       - PROJECT_ID=local-test
#       - REGION=us-central1
#       - DISABLE_TRACING=1
#       - DISABLE_PROFILER=1
#       # Agrega estas variables ficticias para que no lance KeyError
#       - ALLOYDB_DATABASE_NAME=local-db
#       - ALLOYDB_TABLE_NAME=local-table
#       - ALLOYDB_CLUSTER_NAME=local-cluster
#       - ALLOYDB_INSTANCE_NAME=local-instance
#       - ALLOYDB_SECRET_NAME=local-secret
#       - ALLOYDB_CLUSTER_IP=127.0.0.1
#       - ALLOYDB_USER=postgres
#       - ALLOYDB_PASSWORD=postgres
#       - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/google_credentials.json
#     volumes:
#       - ./gcp-dummy-key.json:/tmp/keys/google_credentials.json:ro


  productcatalogservice:
    image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.0
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1

  currencyservice:
    image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.0
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  cartservice:
    image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.0
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  recommendationservice:
    image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.0
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  shippingservice:
    image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.0
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  checkoutservice:
    image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.0
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1

  paymentservice:
    image: gcr.io/google-samples/microservices-demo/paymentservice:v0.10.0
    ports:
      - "50052:50051"
    environment:
      - PORT=50051
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  emailservice:
    image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.0
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  adservice:
    image: gcr.io/google-samples/microservices-demo/adservice:v0.10.0
    ports:
      - "9555:9555"
    environment:
      - PORT=9555
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_TRACING=1
      - DISABLE_PROFILER=1
      - PROJECT_ID=local-test

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"